public without sharing class Lead{
    
    public Lead(){
        
    }
    public Lead(String firstName,String lastName,String company,String email,String phone){
        this.firstName=firstName;
        this.lastName=lastName;
        this.company=company;
        this.email=email;
        this.phone=phone;
    }

    public String firstName

    { get; set; }
    
    public String lastName

    { get; set; }
    
    public String company

    { get; set; }
    
    public String email

    { get; set; }
    
    public String phone

    { get; set; }   
}